# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# raster_2_shp.py
# Created on: 2022-06-23 20:09:26.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------


import arcpy

arcpy.env.workspace = "./png_files"

##Export tfw file from the intput Raster Dataset
arcpy.ExportRasterWorldFile_management("DONE_FIN_95203021_181030z_21_9884_hr4.tif")