# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# raster_2_shp.py
# Created on: 2022-06-23 20:09:26.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
TH_Fold1_REAL_TEST_SA2_IMG1_Post10_png = "D:\\1102_work\\png_2_shp\\png_files\\TH_Fold1_REAL TEST SA2_IMG1_Post10.png"
RasterT_png3 = "D:\\1102_work\\png_2_shp\\Default.gdb\\RasterT_png3"
shp_files = "D:\\1102_work\\png_2_shp\\shp_files"
shp_files__2_ = shp_files

# Process: Raster to Polygon
arcpy.RasterToPolygon_conversion(TH_Fold1_REAL_TEST_SA2_IMG1_Post10_png, RasterT_png3, "SIMPLIFY", "Value", "SINGLE_OUTER_PART", "")

# Process: Feature Class To Shapefile (multiple)
arcpy.FeatureClassToShapefile_conversion("D:\\1102_work\\png_2_shp\\Default.gdb\\RasterT_png3", shp_files)

