# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# raster_2_shp.py
# Created on: 2022-06-23 20:09:26.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------


import arcpy


#edit the following variables to match your use case

arcpy.env.workspace = "."#work space
input_png = "./png_files/test_resized.png"#the resized segmentation mask
polygon = "./Default.gdb/test"#this is the gdb used for this project
shp_files = "./shp_files"#the output dir of the shp file

arcpy.env.overwriteOutput = True#this allows geoprocessing tools to overwrite existing datasets

arcpy.RasterToPolygon_conversion(input_png, polygon, "SIMPLIFY", "Value", "SINGLE_OUTER_PART", "")


arcpy.FeatureClassToShapefile_conversion(polygon, shp_files)

