# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# raster_2_shp.py
# Created on: 2022-06-23 20:09:26.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------


import arcpy



#edit the following variables to match your use case
input_png = "D:\\1102_work\\png_2_shp\\png_files\\TH_Fold1_REAL TEST SA2_IMG1_Post10.png"
polygon = "D:\\1102_work\\png_2_shp\\Default.gdb\\RasterT_png3"
shp_files = "D:\\1102_work\\png_2_shp\\shp_files"



arcpy.RasterToPolygon_conversion(input_png, polygon, "SIMPLIFY", "Value", "SINGLE_OUTER_PART", "")


arcpy.FeatureClassToShapefile_conversion(polygon, shp_files)

